export const Data: Array<string> = [
    'Racing car sprays burning fuel into crowd. Racing car sprays burning fuel into crowd.',
    'Japanese princess to wed commoner.Racing car sprays burning fuel into crowd.',
    'Australian walks 100km after outback crash.Racing car sprays burning fuel into crowd.',
    'Man charg',
    'Los Angel.',
    'Racing car sprays burning fuel into crowd.',
    'Japanese princess to wed commoner.',
    'Australian walks 100km after outback crash.',
    'Man charged over missing wedding girl.',
    'Los Angeles battles huge wildfires.',
    'Racing car sprays burning fuel into crowd.',
    'Japanese princess to wed commoner.',
    'Australian walks 100km after outback crash.',
    'Man charged over missing wedding girl.',
    'Los Angeles battles huge wildfires.',
    'Racing car sprays burning fuel into crowd.',
    'Japanese princess to wed commoner.',
    'Australian walks 100km after outback crash.',
    'Man charged over missing wedding girl.',
    
  ];